// web/src/components/features/booking/BarberOption.vue
<script setup lang="ts">
import { computed } from 'vue';
import { cn } from '../../../utils/cn';
import type { ApiBarber } from '../../../lib/catalog';

const props = defineProps<{ barber: ApiBarber; selected: boolean }>();
defineEmits<{ (e: 'select', id: string): void }>();

const initials = computed(
  () => `${props.barber.firstName.charAt(0)}${props.barber.lastName.charAt(0)}`,
);
const fullName = computed(() => `${props.barber.firstName} ${props.barber.lastName}`);
</script>

<template>
  <button
    type="button"
    :aria-pressed="selected"
    :class="
      cn(
        'flex w-full items-center gap-4 border p-4 text-left',
        selected
          ? 'border-bone bg-bone text-ink'
          : 'border-line bg-surface text-bone hover:border-bone',
      )
    "
    @click="$emit('select', barber.id)"
  >
    <span
      :class="
        cn(
          'flex h-12 w-12 shrink-0 items-center justify-center border text-2xl tracking-widest',
          selected ? 'border-ink bg-ink text-bone' : 'border-line bg-ink text-bone',
        )
      "
      aria-hidden="true"
    >
      {{ initials }}
    </span>
    <span>
      <span class="block text-2xl leading-none tracking-widest">{{ fullName }}</span>
      <span :class="cn('block text-lg tracking-widest', selected ? 'text-ink' : 'text-ash')">
        {{ barber.seniority }}
      </span>
    </span>
  </button>
</template>

// mobile/components/features/booking/BarberOption.tsx
import { Pressable, Text, View } from 'react-native';
import type { ApiBarber } from '@/src/lib/catalog';

export function BarberOption({
  barber,
  selected,
  onSelect,
}: {
  barber: ApiBarber;
  selected: boolean;
  onSelect: (id: string) => void;
}) {
  const initials = `${barber.firstName.charAt(0)}${barber.lastName.charAt(0)}`;
  return (
    <Pressable
      accessibilityRole="button"
      accessibilityState={{ selected }}
      onPress={() => onSelect(barber.id)}
      className={
        selected
          ? 'w-full flex-row items-center gap-4 border border-bone bg-bone p-4'
          : 'w-full flex-row items-center gap-4 border border-line bg-surface p-4'
      }
      style={({ pressed }) => ({ opacity: pressed ? 0.7 : 1 })}
    >
      <View
        className={
          selected
            ? 'h-12 w-12 shrink-0 items-center justify-center border border-ink bg-ink'
            : 'h-12 w-12 shrink-0 items-center justify-center border border-line bg-ink'
        }
      >
        <Text className="font-display text-2xl uppercase tracking-widest text-bone">
          {initials}
        </Text>
      </View>
      <View>
        <Text
          className={
            selected
              ? 'font-display text-2xl uppercase leading-none tracking-widest text-ink'
              : 'font-display text-2xl uppercase leading-none tracking-widest text-bone'
          }
        >
          {barber.firstName} {barber.lastName}
        </Text>
        <Text
          className={
            selected
              ? 'font-display text-lg uppercase tracking-widest text-ink'
              : 'font-display text-lg uppercase tracking-widest text-ash'
          }
        >
          {barber.seniority}
        </Text>
      </View>
    </Pressable>
  );
}
