// web/src/components/features/booking/BookingSummary.vue
<script setup lang="ts">
defineProps<{
  barberName: string;
  serviceName: string;
  durationMin: number;
  price: number;
  dateLabel: string;
  time: string;
}>();
</script>

<template>
  <ul aria-label="Rezime rezervacije" class="border-y border-line">
    <li class="flex items-center justify-between py-2">
      <span class="text-lg tracking-widest text-ash">BERBERIN</span>
      <span class="text-xl tracking-widest text-bone">{{ barberName }}</span>
    </li>
    <li class="flex items-center justify-between border-t border-line py-2">
      <span class="text-lg tracking-widest text-ash">USLUGA</span>
      <span class="text-xl tracking-widest text-bone">{{ serviceName }}</span>
    </li>
    <li class="flex items-center justify-between border-t border-line py-2">
      <span class="text-lg tracking-widest text-ash">KADA</span>
      <span class="text-xl tracking-widest text-bone">{{ dateLabel }} / {{ time }}</span>
    </li>
    <li class="flex items-center justify-between border-t border-line py-2">
      <span class="text-lg tracking-widest text-ash">TRAJANJE</span>
      <span class="text-xl tracking-widest text-bone">{{ durationMin }} MIN</span>
    </li>
    <li class="flex items-center justify-between border-t border-line py-2">
      <span class="text-lg tracking-widest text-ash">UKUPNO</span>
      <span class="text-3xl tracking-widest text-bone">{{ price }}</span>
    </li>
  </ul>
</template>

// mobile/components/features/booking/BookingSummary.tsx
import { Text, View } from 'react-native';

export function BookingSummary({
  barberName,
  serviceName,
  durationMin,
  price,
  dateLabel,
  time,
}: {
  barberName: string;
  serviceName: string;
  durationMin: number;
  price: number;
  dateLabel: string;
  time: string;
}) {
  return (
    <View accessibilityLabel="Rezime rezervacije" className="border-y border-line">
      <SummaryRow label="BERBERIN" value={barberName} />
      <SummaryRow label="USLUGA" value={serviceName} bordered />
      <SummaryRow label="KADA" value={`${dateLabel} / ${time}`} bordered />
      <SummaryRow label="TRAJANJE" value={`${durationMin} MIN`} bordered />
      <View className="flex-row items-center justify-between border-t border-line py-2">
        <Text className="font-display text-lg uppercase tracking-widest text-ash">UKUPNO</Text>
        <Text className="font-display text-3xl uppercase tracking-widest text-blue">{price}</Text>
      </View>
    </View>
  );
}

function SummaryRow({
  label,
  value,
  bordered = false,
}: {
  label: string;
  value: string;
  bordered?: boolean;
}) {
  return (
    <View
      className={
        bordered
          ? 'flex-row items-center justify-between border-t border-line py-2'
          : 'flex-row items-center justify-between py-2'
      }
    >
      <Text className="font-display text-lg uppercase tracking-widest text-ash">{label}</Text>
      <Text className="font-display text-xl uppercase tracking-widest text-bone">{value}</Text>
    </View>
  );
}
