// web/src/components/features/booking/BookingStepper.vue
<script setup lang="ts">
import { Clock, Scissors, Sparkles, Ticket } from '@lucide/vue';
import { cn } from '../../../utils/cn';

defineProps<{ step: number }>();
defineEmits<{ (e: 'go', step: number): void }>();

const steps = [
  { n: 1, label: 'BERBERIN', icon: Scissors },
  { n: 2, label: 'USLUGA', icon: Sparkles },
  { n: 3, label: 'TERMIN', icon: Clock },
  { n: 4, label: 'REZERVACIJA', icon: Ticket },
];
</script>

<template>
  <nav aria-label="Booking steps" class="mt-6 grid grid-cols-4 border border-line">
    <button
      v-for="s in steps"
      :key="s.n"
      type="button"
      :disabled="s.n > step"
      :aria-current="s.n === step ? 'step' : undefined"
      :class="
        cn(
          'flex flex-col items-center border-r border-line py-2 tracking-widest last:border-r-0',
          s.n === step ? 'bg-bone text-ink' : s.n < step ? 'text-bone' : 'text-ash',
          s.n > step && 'opacity-60',
        )
      "
      @click="$emit('go', s.n)"
    >
      <span class="text-sm tracking-widest">0{{ s.n }}</span>
      <span class="text-lg tracking-widest">{{ s.label }}</span>
      <component :is="s.icon" class="mt-1 h-4.5 w-4.5" aria-hidden="true" />
    </button>
  </nav>
</template>

// mobile/components/features/booking/BookingStepper.tsx
import { Pressable, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';

const STEPS: Array<{ n: number; label: string; icon: keyof typeof Ionicons.glyphMap }> = [
  { n: 1, label: 'BERBERIN', icon: 'cut' },
  { n: 2, label: 'USLUGA', icon: 'sparkles' },
  { n: 3, label: 'TERMIN', icon: 'time' },
  { n: 4, label: 'REZERVACIJA', icon: 'ticket' },
];

export function BookingStepper({ step, onGo }: { step: number; onGo: (step: number) => void }) {
  return (
    <View accessibilityLabel="Booking steps" className="mt-6 flex-row border border-line">
      {STEPS.map((s) => {
        const active = s.n === step;
        const done = s.n < step;
        const locked = s.n > step;
        return (
          <Pressable
            key={s.n}
            accessibilityRole="button"
            disabled={locked}
            onPress={() => onGo(s.n)}
            className={
              active
                ? 'flex-1 items-center border-r border-line bg-bone py-2'
                : 'flex-1 items-center border-r border-line py-2'
            }
            style={({ pressed }) => ({ opacity: locked ? 0.6 : pressed ? 0.7 : 1 })}
          >
            <Text
              className={
                active
                  ? 'font-display text-sm uppercase tracking-widest text-ink'
                  : done
                    ? 'font-display text-sm uppercase tracking-widest text-bone'
                    : 'font-display text-sm uppercase tracking-widest text-ash'
              }
            >
              0{s.n}
            </Text>
            <Text
              className={
                active
                  ? 'font-display text-lg uppercase tracking-widest text-ink'
                  : done
                    ? 'font-display text-lg uppercase tracking-widest text-bone'
                    : 'font-display text-lg uppercase tracking-widest text-ash'
              }
            >
              {s.label}
            </Text>
            <Ionicons
              name={s.icon}
              size={16}
              color={active ? '#080808' : done ? '#F5F5F0' : '#A1A1A1'}
            />
          </Pressable>
        );
      })}
    </View>
  );
}
