// web/src/components/features/booking/TimeGrid.vue
<script setup lang="ts">
import { cn } from '../../../utils/cn';
import type { TimeSlot } from '../../../data/mock';

defineProps<{ slots: TimeSlot[]; selectedTime: string | null }>();
defineEmits<{ (e: 'select', time: string): void }>();
</script>

<template>
  <div class="grid grid-cols-3 gap-2 sm:grid-cols-4" role="group" aria-label="Pick a time">
    <button
      v-for="s in slots"
      :key="s.id"
      type="button"
      :disabled="!s.available"
      :aria-pressed="selectedTime === s.time"
      :class="
        cn(
          'border py-2 text-xl tracking-widest',
          selectedTime === s.time
            ? 'border-bone bg-bone text-ink'
            : 'border-line bg-surface text-bone hover:border-bone',
          !s.available && 'cursor-not-allowed opacity-30 hover:border-line',
          !s.available && 'line-through',
        )
      "
      @click="$emit('select', s.time)"
    >
      {{ s.time }}
    </button>
  </div>
</template>

// mobile/components/features/booking/TimeGrid.tsx
import { Pressable, Text, View } from 'react-native';
import type { TimeSlot } from '@/src/lib/days';

export function TimeGrid({
  slots,
  selectedTime,
  onSelect,
}: {
  slots: TimeSlot[];
  selectedTime: string | null;
  onSelect: (time: string) => void;
}) {
  return (
    <View accessibilityLabel="Pick a time" className="flex-row flex-wrap gap-2">
      {slots.map((s) => {
        const active = selectedTime === s.time;
        return (
          <Pressable
            key={s.id}
            accessibilityRole="button"
            accessibilityState={{ selected: active, disabled: !s.available }}
            disabled={!s.available}
            onPress={() => onSelect(s.time)}
            className={
              active
                ? 'w-[31%] border border-bone bg-bone py-2'
                : s.available
                  ? 'w-[31%] border border-line bg-surface py-2'
                  : 'w-[31%] border border-line bg-surface py-2 opacity-30'
            }
            style={({ pressed }) => ({ opacity: !s.available ? 0.3 : pressed ? 0.7 : 1 })}
          >
            <Text
              className={
                active
                  ? 'text-center font-display text-xl uppercase tracking-widest text-ink'
                  : s.available
                    ? 'text-center font-display text-xl uppercase tracking-widest text-bone'
                    : 'text-center font-display text-xl uppercase tracking-widest text-bone line-through'
              }
            >
              {s.time}
            </Text>
          </Pressable>
        );
      })}
    </View>
  );
}
