// mobile/components/features/booking/DateStrip.tsx
import { Pressable, ScrollView, Text } from 'react-native';
import type { DayOption } from '@/src/lib/days';

export function DateStrip({
  days,
  selectedIso,
  onSelect,
}: {
  days: DayOption[];
  selectedIso: string | null;
  onSelect: (iso: string) => void;
}) {
  return (
    <ScrollView
      horizontal
      showsHorizontalScrollIndicator={false}
      accessibilityLabel="Pick a day"
      contentContainerStyle={{ gap: 8, paddingBottom: 8 }}
    >
      {days.map((d) => {
        const active = selectedIso === d.iso;
        return (
          <Pressable
            key={d.iso}
            accessibilityRole="button"
            accessibilityState={{ selected: active, disabled: d.closed }}
            disabled={d.closed}
            onPress={() => onSelect(d.iso)}
            className={
              active
                ? 'w-16 shrink-0 items-center border border-bone bg-bone py-2'
                : d.closed
                  ? 'w-16 shrink-0 items-center border border-line bg-surface py-2 opacity-40'
                  : 'w-16 shrink-0 items-center border border-line bg-surface py-2'
            }
            style={({ pressed }) => ({ opacity: d.closed ? 0.4 : pressed ? 0.7 : 1 })}
          >
            <Text
              className={
                active
                  ? 'font-display text-base uppercase tracking-widest text-ink'
                  : 'font-display text-base uppercase tracking-widest text-ash'
              }
            >
              {d.weekday}
            </Text>
            <Text
              className={
                active
                  ? 'font-display text-3xl uppercase leading-none tracking-widest text-ink'
                  : 'font-display text-3xl uppercase leading-none tracking-widest text-bone'
              }
            >
              {d.dayNum}
            </Text>
            <Text
              className={
                active
                  ? 'font-display text-base uppercase tracking-widest text-ink'
                  : 'font-display text-base uppercase tracking-widest text-ash'
              }
            >
              {d.closed ? 'NE RADI' : d.month}
            </Text>
          </Pressable>
        );
      })}
    </ScrollView>
  );
}

// web/src/components/features/booking/DateStrip.vue
<script setup lang="ts">
import { cn } from '../../../utils/cn';
import type { DayOption } from '../../../data/mock';

defineProps<{ days: DayOption[]; selectedIso: string | null }>();
defineEmits<{ (e: 'select', iso: string): void }>();
</script>

<template>
  <div class="flex gap-2 overflow-x-auto pb-2" role="group" aria-label="Pick a day">
    <button
      v-for="d in days"
      :key="d.iso"
      type="button"
      :disabled="d.closed"
      :aria-pressed="selectedIso === d.iso"
      :class="
        cn(
          'flex w-16 shrink-0 flex-col items-center border py-2 tracking-widest',
          selectedIso === d.iso
            ? 'border-bone bg-bone text-ink'
            : 'border-line bg-surface text-bone hover:border-bone',
          d.closed && 'cursor-not-allowed opacity-40 hover:border-line',
        )
      "
      @click="$emit('select', d.iso)"
    >
      <span :class="cn('text-base tracking-widest', selectedIso === d.iso ? 'text-ink' : 'text-ash')">
        {{ d.weekday }}
      </span>
      <span class="text-3xl leading-none tracking-widest">{{ d.dayNum }}</span>
      <span :class="cn('text-base tracking-widest', selectedIso === d.iso ? 'text-ink' : 'text-ash')">
        {{ d.closed ? 'NE RADI' : d.month }}
      </span>
    </button>
  </div>
</template>
