// mobile/components/features/booking/ServiceOption.tsx
import { Pressable, Text, View } from 'react-native';
import type { ApiService } from '@/src/lib/catalog';

export function ServiceOption({
  service,
  selected,
  onSelect,
}: {
  service: ApiService;
  selected: boolean;
  onSelect: (id: string) => void;
}) {
  return (
    <Pressable
      accessibilityRole="button"
      accessibilityState={{ selected }}
      onPress={() => onSelect(service.id)}
      className={
        selected
          ? 'w-full flex-row items-center justify-between gap-3 border border-bone bg-bone p-4'
          : 'w-full flex-row items-center justify-between gap-3 border border-line bg-surface p-4'
      }
      style={({ pressed }) => ({ opacity: pressed ? 0.7 : 1 })}
    >
      <View>
        <Text
          className={
            selected
              ? 'font-display text-2xl uppercase leading-none tracking-widest text-ink'
              : 'font-display text-2xl uppercase leading-none tracking-widest text-bone'
          }
        >
          {service.name}
        </Text>
        <Text
          className={
            selected
              ? 'font-display text-lg uppercase tracking-widest text-ink'
              : 'font-display text-lg uppercase tracking-widest text-ash'
          }
        >
          {service.durationMinutes} MIN
        </Text>
      </View>
      <Text
        className={
          selected
            ? 'shrink-0 font-display text-3xl uppercase tracking-widest text-ink'
            : 'shrink-0 font-display text-3xl uppercase tracking-widest text-blue'
        }
      >
        {service.price}
      </Text>
    </Pressable>
  );
}

// web/src/components/features/booking/ServiceOption.vue
<script setup lang="ts">
import { cn } from '../../../utils/cn';
import type { ApiService } from '../../../lib/catalog';

defineProps<{ service: ApiService; selected: boolean }>();
defineEmits<{ (e: 'select', id: string): void }>();
</script>

<template>
  <button
    type="button"
    :aria-pressed="selected"
    :class="
      cn(
        'flex w-full items-center justify-between gap-3 border p-4 text-left',
        selected
          ? 'border-bone bg-bone text-ink'
          : 'border-line bg-surface text-bone hover:border-bone',
      )
    "
    @click="$emit('select', service.id)"
  >
    <span>
      <span class="block text-2xl leading-none tracking-widest">{{ service.name }}</span>
      <span :class="cn('block text-lg tracking-widest', selected ? 'text-ink' : 'text-ash')">
        {{ service.durationMinutes }} MIN
      </span>
    </span>
    <span class="shrink-0 text-3xl tracking-widest">{{ service.price }}</span>
  </button>
</template>
